// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateWorkflowApiV1WorkflowsPostData, CreateWorkflowApiV1WorkflowsPostErrors, CreateWorkflowApiV1WorkflowsPostResponses, DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteData, DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteErrors, DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponses, GetAllRunsApiV1DataRunsGetData, GetAllRunsApiV1DataRunsGetResponses, GetAllRunsApiV1DataStepsSchemaGetData, GetAllRunsApiV1DataStepsSchemaGetResponses, GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetData, GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetErrors, GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponses, GetExcelFileSheetsApiV1DataFilesSheetsPostData, GetExcelFileSheetsApiV1DataFilesSheetsPostErrors, GetExcelFileSheetsApiV1DataFilesSheetsPostResponses, GetWorkflowApiV1WorkflowsWorkflowNameGetData, GetWorkflowApiV1WorkflowsWorkflowNameGetErrors, GetWorkflowApiV1WorkflowsWorkflowNameGetResponses, ListWorkflowsApiV1WorkflowsGetData, ListWorkflowsApiV1WorkflowsGetResponses, RunWorkflowApiV1RunsWorkflowsWorkflowNamePostData, RunWorkflowApiV1RunsWorkflowsWorkflowNamePostErrors, RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponses, UpdateWorkflowApiV1WorkflowsWorkflowNamePutData, UpdateWorkflowApiV1WorkflowsWorkflowNamePutErrors, UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Workflows
 */
export const listWorkflowsApiV1WorkflowsGet = <ThrowOnError extends boolean = false>(options?: Options<ListWorkflowsApiV1WorkflowsGetData, ThrowOnError>): RequestResult<ListWorkflowsApiV1WorkflowsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListWorkflowsApiV1WorkflowsGetResponses, unknown, ThrowOnError>({ url: '/api/v1/workflows', ...options });

/**
 * Create Workflow
 */
export const createWorkflowApiV1WorkflowsPost = <ThrowOnError extends boolean = false>(options: Options<CreateWorkflowApiV1WorkflowsPostData, ThrowOnError>): RequestResult<CreateWorkflowApiV1WorkflowsPostResponses, CreateWorkflowApiV1WorkflowsPostErrors, ThrowOnError> => (options.client ?? client).post<CreateWorkflowApiV1WorkflowsPostResponses, CreateWorkflowApiV1WorkflowsPostErrors, ThrowOnError>({
    url: '/api/v1/workflows',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Workflow
 */
export const deleteWorkflowApiV1WorkflowsWorkflowNameDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteData, ThrowOnError>): RequestResult<DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponses, DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteErrors, ThrowOnError> => (options.client ?? client).delete<DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponses, DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_name}', ...options });

/**
 * Get Workflow
 */
export const getWorkflowApiV1WorkflowsWorkflowNameGet = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowApiV1WorkflowsWorkflowNameGetData, ThrowOnError>): RequestResult<GetWorkflowApiV1WorkflowsWorkflowNameGetResponses, GetWorkflowApiV1WorkflowsWorkflowNameGetErrors, ThrowOnError> => (options.client ?? client).get<GetWorkflowApiV1WorkflowsWorkflowNameGetResponses, GetWorkflowApiV1WorkflowsWorkflowNameGetErrors, ThrowOnError>({ url: '/api/v1/workflows/{workflow_name}', ...options });

/**
 * Update Workflow
 */
export const updateWorkflowApiV1WorkflowsWorkflowNamePut = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkflowApiV1WorkflowsWorkflowNamePutData, ThrowOnError>): RequestResult<UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponses, UpdateWorkflowApiV1WorkflowsWorkflowNamePutErrors, ThrowOnError> => (options.client ?? client).put<UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponses, UpdateWorkflowApiV1WorkflowsWorkflowNamePutErrors, ThrowOnError>({
    url: '/api/v1/workflows/{workflow_name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run Workflow
 */
export const runWorkflowApiV1RunsWorkflowsWorkflowNamePost = <ThrowOnError extends boolean = false>(options: Options<RunWorkflowApiV1RunsWorkflowsWorkflowNamePostData, ThrowOnError>): RequestResult<RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponses, RunWorkflowApiV1RunsWorkflowsWorkflowNamePostErrors, ThrowOnError> => (options.client ?? client).post<RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponses, RunWorkflowApiV1RunsWorkflowsWorkflowNamePostErrors, ThrowOnError>({
    url: '/api/v1/runs/workflows/{workflow_name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Cached Preview
 */
export const getCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGet = <ThrowOnError extends boolean = false>(options: Options<GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetData, ThrowOnError>): RequestResult<GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponses, GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetErrors, ThrowOnError> => (options.client ?? client).get<GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponses, GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetErrors, ThrowOnError>({ url: '/api/v1/data/workflows/{workflow_name}/preview', ...options });

/**
 * Get All Runs
 */
export const getAllRunsApiV1DataRunsGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllRunsApiV1DataRunsGetData, ThrowOnError>): RequestResult<GetAllRunsApiV1DataRunsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllRunsApiV1DataRunsGetResponses, unknown, ThrowOnError>({ url: '/api/v1/data/runs', ...options });

/**
 * Get All Runs
 */
export const getAllRunsApiV1DataStepsSchemaGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllRunsApiV1DataStepsSchemaGetData, ThrowOnError>): RequestResult<GetAllRunsApiV1DataStepsSchemaGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllRunsApiV1DataStepsSchemaGetResponses, unknown, ThrowOnError>({ url: '/api/v1/data/steps_schema', ...options });

/**
 * Get Excel File Sheets
 */
export const getExcelFileSheetsApiV1DataFilesSheetsPost = <ThrowOnError extends boolean = false>(options: Options<GetExcelFileSheetsApiV1DataFilesSheetsPostData, ThrowOnError>): RequestResult<GetExcelFileSheetsApiV1DataFilesSheetsPostResponses, GetExcelFileSheetsApiV1DataFilesSheetsPostErrors, ThrowOnError> => (options.client ?? client).post<GetExcelFileSheetsApiV1DataFilesSheetsPostResponses, GetExcelFileSheetsApiV1DataFilesSheetsPostErrors, ThrowOnError>({
    url: '/api/v1/data/files/sheets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
