// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CachedPreview
 */
export type CachedPreview = {
    /**
     * Data
     */
    data: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Frame Schema
     */
    frame_schema: {
        [key: string]: unknown;
    };
    /**
     * Row Count
     */
    row_count?: number;
    /**
     * Preview Limit
     */
    preview_limit?: number;
    /**
     * Stored At
     */
    stored_at?: string;
};

/**
 * ExcelSheetsRequest
 */
export type ExcelSheetsRequest = {
    /**
     * Path
     */
    path: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MultiSourcesStepConfig
 *
 * Step configuration for steps that contain nested source steps.
 *
 * This is used by transformations that need more than one input source, such
 * as joins or concatenations.
 */
export type MultiSourcesStepConfig = {
    /**
     * Step Id
     */
    step_id?: string;
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    };
    /**
     * Sources
     */
    sources: Array<StepConfig>;
    [key: string]: unknown;
};

/**
 * StepConfig
 *
 * Raw workflow step definition loaded from a workflow file.
 *
 * This model represents the generic configuration shape used in YAML or JSON
 * workflow definitions. Concrete step parameters are stored in `parameters`
 * and later validated against the step-specific `config_model`.
 *
 * Extra fields are allowed to keep the workflow format extensible.
 */
export type StepConfig = {
    /**
     * Step Id
     */
    step_id?: string;
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    };
    [key: string]: unknown;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Workflow
 *
 * Declarative workflow definition.
 *
 * A workflow contains an ordered list of step configurations. The compiler
 * turns this definition into an executable workflow plan.
 */
export type Workflow = {
    /**
     * Name
     */
    name: string;
    /**
     * Steps
     */
    steps?: Array<StepConfig | MultiSourcesStepConfig>;
};

/**
 * WorkflowCreateRequest
 */
export type WorkflowCreateRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Content
     */
    content: string;
};

/**
 * WorkflowErrorContext
 *
 * Structured error context captured when workflow execution fails.
 *
 * The error context enriches raw exceptions with step and frame information,
 * making it easier for the server or UI layer to show useful diagnostics.
 */
export type WorkflowErrorContext = {
    /**
     * Error
     */
    error: string;
    /**
     * Step Id
     */
    step_id: string;
    /**
     * Step Name
     */
    step_name: string;
    /**
     * Frame Schema
     */
    frame_schema?: {
        [key: string]: string;
    } | null;
};

/**
 * WorkflowListResponse
 */
export type WorkflowListResponse = {
    /**
     * Workflows
     */
    workflows: Array<WorkflowSummary>;
};

/**
 * WorkflowResponse
 */
export type WorkflowResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    content: Workflow;
};

/**
 * WorkflowRunRequest
 */
export type WorkflowRunRequest = {
    /**
     * Print Plan
     */
    print_plan?: boolean;
    /**
     * Preview Limit
     */
    preview_limit?: number;
    /**
     * Inspect
     */
    inspect?: boolean;
};

/**
 * WorkflowRunResponse
 */
export type WorkflowRunResponse = {
    /**
     * Workflow Name
     */
    workflow_name: string;
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Preview
     */
    preview?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Row Count
     */
    row_count?: number | null;
};

/**
 * WorkflowRunResult
 *
 * Result of a workflow execution.
 *
 * This model is returned by the runner and can be serialized by higher-level
 * layers such as the server or CLI.
 */
export type WorkflowRunResult = {
    /**
     * Run Id
     */
    run_id?: string;
    /**
     * Name
     */
    name: string;
    status?: WorkflowStatus;
    /**
     * Preview
     */
    preview?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Row Count
     */
    row_count?: number | null;
    error?: WorkflowErrorContext | null;
    statistics?: WorkflowRuntimeStatistics;
    /**
     * Success
     *
     * Return whether the workflow finished successfully.
     *
     * Returns:
     * `True` when status is `success`, otherwise `False`.
     */
    readonly success: boolean;
};

/**
 * WorkflowRuntimeStatistics
 *
 * Runtime statistics collected for a workflow execution.
 */
export type WorkflowRuntimeStatistics = {
    /**
     * Total Steps
     */
    total_steps?: number;
    /**
     * System Steps
     */
    system_steps?: number;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Ended At
     */
    ended_at?: string | null;
    /**
     * Total Time
     */
    total_time?: number;
};

/**
 * WorkflowStatus
 *
 * Execution status of a workflow run.
 */
export type WorkflowStatus = 'created' | 'success' | 'failed' | 'waiting' | 'running' | 'cancelled';

/**
 * WorkflowSummary
 */
export type WorkflowSummary = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
};

/**
 * WorkflowUpdateRequest
 */
export type WorkflowUpdateRequest = {
    /**
     * Content
     */
    content: string;
};

/**
 * WorkflowRunResult
 *
 * Result of a workflow execution.
 *
 * This model is returned by the runner and can be serialized by higher-level
 * layers such as the server or CLI.
 */
export type WorkflowRunResultWritable = {
    /**
     * Run Id
     */
    run_id?: string;
    /**
     * Name
     */
    name: string;
    status?: WorkflowStatus;
    /**
     * Preview
     */
    preview?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Row Count
     */
    row_count?: number | null;
    error?: WorkflowErrorContext | null;
    statistics?: WorkflowRuntimeStatistics;
};

export type ListWorkflowsApiV1WorkflowsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workflows';
};

export type ListWorkflowsApiV1WorkflowsGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowListResponse;
};

export type ListWorkflowsApiV1WorkflowsGetResponse = ListWorkflowsApiV1WorkflowsGetResponses[keyof ListWorkflowsApiV1WorkflowsGetResponses];

export type CreateWorkflowApiV1WorkflowsPostData = {
    body: WorkflowCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/workflows';
};

export type CreateWorkflowApiV1WorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowApiV1WorkflowsPostError = CreateWorkflowApiV1WorkflowsPostErrors[keyof CreateWorkflowApiV1WorkflowsPostErrors];

export type CreateWorkflowApiV1WorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: WorkflowResponse;
};

export type CreateWorkflowApiV1WorkflowsPostResponse = CreateWorkflowApiV1WorkflowsPostResponses[keyof CreateWorkflowApiV1WorkflowsPostResponses];

export type DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Name
         */
        workflow_name: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_name}';
};

export type DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteError = DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteErrors[keyof DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteErrors];

export type DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponse = DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponses[keyof DeleteWorkflowApiV1WorkflowsWorkflowNameDeleteResponses];

export type GetWorkflowApiV1WorkflowsWorkflowNameGetData = {
    body?: never;
    path: {
        /**
         * Workflow Name
         */
        workflow_name: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_name}';
};

export type GetWorkflowApiV1WorkflowsWorkflowNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowApiV1WorkflowsWorkflowNameGetError = GetWorkflowApiV1WorkflowsWorkflowNameGetErrors[keyof GetWorkflowApiV1WorkflowsWorkflowNameGetErrors];

export type GetWorkflowApiV1WorkflowsWorkflowNameGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResponse;
};

export type GetWorkflowApiV1WorkflowsWorkflowNameGetResponse = GetWorkflowApiV1WorkflowsWorkflowNameGetResponses[keyof GetWorkflowApiV1WorkflowsWorkflowNameGetResponses];

export type UpdateWorkflowApiV1WorkflowsWorkflowNamePutData = {
    body: WorkflowUpdateRequest;
    path: {
        /**
         * Workflow Name
         */
        workflow_name: string;
    };
    query?: never;
    url: '/api/v1/workflows/{workflow_name}';
};

export type UpdateWorkflowApiV1WorkflowsWorkflowNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkflowApiV1WorkflowsWorkflowNamePutError = UpdateWorkflowApiV1WorkflowsWorkflowNamePutErrors[keyof UpdateWorkflowApiV1WorkflowsWorkflowNamePutErrors];

export type UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResponse;
};

export type UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponse = UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponses[keyof UpdateWorkflowApiV1WorkflowsWorkflowNamePutResponses];

export type RunWorkflowApiV1RunsWorkflowsWorkflowNamePostData = {
    body: WorkflowRunRequest;
    path: {
        /**
         * Workflow Name
         */
        workflow_name: string;
    };
    query?: never;
    url: '/api/v1/runs/workflows/{workflow_name}';
};

export type RunWorkflowApiV1RunsWorkflowsWorkflowNamePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunWorkflowApiV1RunsWorkflowsWorkflowNamePostError = RunWorkflowApiV1RunsWorkflowsWorkflowNamePostErrors[keyof RunWorkflowApiV1RunsWorkflowsWorkflowNamePostErrors];

export type RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponses = {
    /**
     * Successful Response
     */
    200: WorkflowRunResponse;
};

export type RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponse = RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponses[keyof RunWorkflowApiV1RunsWorkflowsWorkflowNamePostResponses];

export type GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetData = {
    body?: never;
    path: {
        /**
         * Workflow Name
         */
        workflow_name: string;
    };
    query?: never;
    url: '/api/v1/data/workflows/{workflow_name}/preview';
};

export type GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetError = GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetErrors[keyof GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetErrors];

export type GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponses = {
    /**
     * Successful Response
     */
    200: CachedPreview;
};

export type GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponse = GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponses[keyof GetCachedPreviewApiV1DataWorkflowsWorkflowNamePreviewGetResponses];

export type GetAllRunsApiV1DataRunsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/data/runs';
};

export type GetAllRunsApiV1DataRunsGetResponses = {
    /**
     * Response Get All Runs Api V1 Data Runs Get
     *
     * Successful Response
     */
    200: Array<WorkflowRunResult>;
};

export type GetAllRunsApiV1DataRunsGetResponse = GetAllRunsApiV1DataRunsGetResponses[keyof GetAllRunsApiV1DataRunsGetResponses];

export type GetAllRunsApiV1DataStepsSchemaGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/data/steps_schema';
};

export type GetAllRunsApiV1DataStepsSchemaGetResponses = {
    /**
     * Response Get All Runs Api V1 Data Steps Schema Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetAllRunsApiV1DataStepsSchemaGetResponse = GetAllRunsApiV1DataStepsSchemaGetResponses[keyof GetAllRunsApiV1DataStepsSchemaGetResponses];

export type GetExcelFileSheetsApiV1DataFilesSheetsPostData = {
    body: ExcelSheetsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/data/files/sheets';
};

export type GetExcelFileSheetsApiV1DataFilesSheetsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExcelFileSheetsApiV1DataFilesSheetsPostError = GetExcelFileSheetsApiV1DataFilesSheetsPostErrors[keyof GetExcelFileSheetsApiV1DataFilesSheetsPostErrors];

export type GetExcelFileSheetsApiV1DataFilesSheetsPostResponses = {
    /**
     * Response Get Excel File Sheets Api V1 Data Files Sheets Post
     *
     * Successful Response
     */
    200: Array<string>;
};

export type GetExcelFileSheetsApiV1DataFilesSheetsPostResponse = GetExcelFileSheetsApiV1DataFilesSheetsPostResponses[keyof GetExcelFileSheetsApiV1DataFilesSheetsPostResponses];
