site_name: Crucible
site_description: Local-first workflow engine for data transformation and reporting
repo_url: https://github.com/Nietaktowny/Crucible
theme:
  palette:
    scheme: slate
    primary: #0F172A
    secondary: #F59E0B
  name: material
  logo: assets/crucible-logo.png
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - Getting Started:
      - getting-started.md
  - User Guide:
      - workflows.md
  - Code reference:
    - reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            filters: []
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

extra_css:
  - stylesheets/extra.css